--사원의 연봉을 구하는 FUNCTION
create or replace FUNCTION GET_ANNUAL_SAL(V_EMPNO NUMBER)
    RETURN NUMBER IS V_SAL NUMBER;
BEGIN
    SELECT (SAL + NVL(COMM, 0)) * 12 INTO V_SAL
      FROM EMP 
     WHERE EMPNO = V_EMPNO;
    RETURN V_SAL;
END;