--사원의 퇴직급여를 구하는 FUNCTION
--35442
create or replace FUNCTION GET_RETIRE_MONEY(V_EMPNO NUMBER)
    RETURN NUMBER IS V_SAL NUMBER;
BEGIN
    SELECT ROUND((SAL + NVL(COMM, 0)) * ROUND(MONTHS_BETWEEN(SYSDATE, HIREDATE), 0) / 12, 0)
      INTO V_SAL
      FROM EMP 
     WHERE EMPNO = V_EMPNO;
    RETURN V_SAL;
END;