--PACKAGE 생성 (BODY)
CREATE OR REPLACE PACKAGE BODY EMP_MGMT AS
    --사원 급여 조정 PROCEDURE 
    PROCEDURE ADJUST_SAL
        (V_FLAG VARCHAR2, V_EMPNO NUMBER, V_PCT NUMBER) AS
    BEGIN
        IF V_FLAG = 'INCREASE' THEN
            UPDATE emp SET SAL = SAL + (SAL * (V_PCT/100))
            WHERE empno = V_EMPNO;
        ELSE
            UPDATE emp SET SAL = SAL - (SAL * (V_PCT/100))
            WHERE empno = V_EMPNO;
        END IF;
    END;
    
    --사원의 연봉을 구하는 FUNCTION
    FUNCTION GET_ANNUAL_SAL(V_EMPNO NUMBER)
        RETURN NUMBER IS V_SAL NUMBER;
    BEGIN
        SELECT (SAL + NVL(COMM, 0)) * 12 INTO V_SAL
          FROM EMP 
         WHERE EMPNO = V_EMPNO;
        RETURN V_SAL;
    END;
    
    --사원의 퇴직급여를 구하는 FUNCTION
    --35442
    FUNCTION GET_RETIRE_MONEY(V_EMPNO NUMBER)
        RETURN NUMBER IS V_SAL NUMBER;
    BEGIN
        SELECT ROUND((SAL + NVL(COMM, 0)) * ROUND(MONTHS_BETWEEN(SYSDATE, HIREDATE), 0) / 12, 0)
          INTO V_SAL
          FROM EMP 
         WHERE EMPNO = V_EMPNO;
        RETURN V_SAL;
    END;
    
    --사원 정보를 삭제하는 PROCEDURE 
    PROCEDURE REMOVE_EMP
        (V_EMPNO NUMBER) AS
    BEGIN
        DELETE FROM EMP 
         WHERE empno = V_EMPNO;
    END;
    
    --사원의 입사일자를 구하는 FUNCTION
    FUNCTION GET_HIREDATE(V_EMPNO NUMBER, V_FMT VARCHAR2)
        RETURN VARCHAR2 IS V_HIREDATE VARCHAR2(20);
    BEGIN
        SELECT TO_CHAR(HIREDATE, V_FMT)
          INTO V_HIREDATE
          FROM EMP 
         WHERE EMPNO = V_EMPNO;
        RETURN V_HIREDATE;
    END;
END;