--PACKAGE 생성 (HEADER)
CREATE OR REPLACE PACKAGE EMP_MGMT AS
    PROCEDURE ADJUST_SAL(V_FLAG VARCHAR2, V_EMPNO NUMBER, V_PCT NUMBER);
    FUNCTION GET_ANNUAL_SAL(V_EMPNO NUMBER) RETURN NUMBER;
    FUNCTION GET_RETIRE_MONEY(V_EMPNO NUMBER) RETURN NUMBER;
    FUNCTION GET_HIREDATE(V_EMPNO NUMBER, V_FMT VARCHAR2) RETURN VARCHAR2;
    PROCEDURE REMOVE_EMP(V_EMPNO NUMBER);
END EMP_MGMT;